launchpad: Update the esp-idf image versions

diff --git a/.github/workflows/launchpad.yml b/.github/workflows/launchpad.yml
--- a/.github/workflows/launchpad.yml
+++ b/.github/workflows/launchpad.yml
@@ -43,7 +43,7 @@ jobs:
 
     runs-on: ubuntu-latest
     container:
-      image: espressif/idf:v5.4.2
+      image: espressif/idf:v5.5.1
     strategy:
       matrix:
         example: [fan, led_light, multi_device, switch, temperature_sensor]
@@ -91,7 +91,7 @@ jobs:
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     container:
-      image: espressif/esp-matter:latest
+      image: espressif/idf:v5.5.1
 
     steps:
       - uses: actions/checkout@v4
@@ -122,6 +122,11 @@ jobs:
           echo "" >> build_cfg.md
 
           cat $ESP_RMAKER_PATH/tools/launchpad/app_link_guide.md >> build_cfg.md
+          
+          if ! command -v tree >/dev/null 2>&1; then
+            echo "tree not found, installing..."
+            apt-get update && apt-get install -y tree
+          fi
 
           tree -H '.' -L 1 --noreport -T 'ESP RainMaker Launchpad Artifacts' -shi --charset utf-8 -I "index.html" -o index.html
 
